blank_issues_enabled: false

contact_links:
  - name: Ask questions
    url: https://github.com/dynbox/{{PROJECT_NAME}}/blob/dev/CONTRIBUTING.md#question
    about: ğŸ™‹â€â™‚ï¸ Ask questions and seek assistance